\echo Running migrations
\set ON_ERROR_STOP on
\ir migrations/001_create_roles_table.sql
\ir migrations/002_create_permissions_table.sql
\ir migrations/003_create_users_table.sql
\ir migrations/004_create_companies_table.sql
\ir migrations/005_create_plans_table.sql
\ir migrations/006_create_subscriptions_table.sql
\ir migrations/007_create_vcard_templates_table.sql
\ir migrations/008_create_vcards_table.sql
\ir migrations/009_create_qrcodes_table.sql
\ir migrations/010_create_nfc_orders_table.sql
\ir migrations/011_create_payments_table.sql
\ir migrations/012_create_invoices_table.sql
\ir migrations/013_create_notifications_table.sql
\ir migrations/014_create_activity_logs_table.sql
\ir migrations/015_create_settings_table.sql
\ir migrations/016_create_business_cards_table.sql
\ir migrations/017_create_card_social_links_table.sql
\ir migrations/018_create_card_gallery_table.sql
\ir migrations/019_create_nfc_cards_table.sql
\ir migrations/020_create_contacts_table.sql
\ir migrations/021_create_analytics_table.sql
\ir migrations/022_create_transactions_table.sql
\ir migrations/023_create_role_permissions_table.sql
\ir migrations/024_create_nfc_products_table.sql
\ir migrations/025_link_nfc_orders_to_products.sql
\ir migrations/026_extend_payments_for_manual_review.sql
\ir migrations/027_create_payouts_table.sql
\ir migrations/028_create_withdrawals_table.sql
\ir migrations/029_create_affiliate_program_tables.sql
\ir migrations/030_create_coupon_management_tables.sql
\ir migrations/031_create_saved_reports_tables.sql
\ir migrations/032_seed_platform_settings_and_permissions.sql
\ir migrations/033_create_auth_sessions_table.sql
\ir migrations/034_create_appointments_table.sql
\ir migrations/035_add_category_to_nfc_products.sql
\ir migrations/036_link_contacts_to_vcards.sql
\ir migrations/037_configure_manual_subscription_payments.sql
\ir migrations/038_complete_affiliate_workflow.sql
\ir migrations/039_credit_approved_affiliate_subscriptions.sql
\ir migrations/040_add_nfc_order_payments.sql
\ir migrations/041_harden_nfc_order_workflow.sql
\ir migrations/042_add_corporate_ceo_vcard_template.sql
\ir migrations/043_add_user_currency_preference.sql
\ir migrations/044_complete_user_coupon_checkout.sql
\ir migrations/045_add_vcard_engagement_tracking.sql
\ir migrations/046_complete_vcard_analytics_pipeline.sql
\ir migrations/047_create_virtual_nfc_designs.sql
\ir migrations/048_add_plan_storage_limits.sql
\ir migrations/049_create_user_settings.sql
\ir migrations/050_add_multi_currency_plan_prices.sql
\ir migrations/051_add_lkr_exchange_and_nfc_shipping.sql
\ir migrations/052_add_vcard_public_slugs.sql
\ir migrations/053_prefer_readable_vcard_slugs.sql
\ir migrations/054_replace_with_final_vcard_templates.sql
\ir migrations/055_optimize_user_notifications.sql
\ir migrations/056_add_vcard_qualifications.sql
\ir migrations/057_add_appointment_service.sql
\ir migrations/058_add_withdrawal_transfer_receipts.sql
\ir migrations/059_normalize_active_withdrawals_to_bank_transfer.sql
\ir migrations/060_add_domestic_nfc_delivery_fee.sql
\ir migrations/061_add_website_contact_messages.sql
\ir migrations/062_add_coupon_user_visibility.sql

\ir migrations/063_add_password_recovery.sql
