\echo Running migrations
\set ON_ERROR_STOP on
\i c:/Syscare Projects/digital-business-card-saas/database/migrations/001_create_roles_table.sql
\i c:/Syscare Projects/digital-business-card-saas/database/migrations/002_create_permissions_table.sql
\i c:/Syscare Projects/digital-business-card-saas/database/migrations/003_create_users_table.sql
\i c:/Syscare Projects/digital-business-card-saas/database/migrations/004_create_companies_table.sql
\i c:/Syscare Projects/digital-business-card-saas/database/migrations/005_create_plans_table.sql
\i c:/Syscare Projects/digital-business-card-saas/database/migrations/006_create_subscriptions_table.sql
\i c:/Syscare Projects/digital-business-card-saas/database/migrations/007_create_vcard_templates_table.sql
\i c:/Syscare Projects/digital-business-card-saas/database/migrations/008_create_vcards_table.sql
\i c:/Syscare Projects/digital-business-card-saas/database/migrations/009_create_qrcodes_table.sql
\i c:/Syscare Projects/digital-business-card-saas/database/migrations/010_create_nfc_orders_table.sql
\i c:/Syscare Projects/digital-business-card-saas/database/migrations/011_create_payments_table.sql
\i c:/Syscare Projects/digital-business-card-saas/database/migrations/012_create_invoices_table.sql
\i c:/Syscare Projects/digital-business-card-saas/database/migrations/013_create_notifications_table.sql
\i c:/Syscare Projects/digital-business-card-saas/database/migrations/014_create_activity_logs_table.sql
\i c:/Syscare Projects/digital-business-card-saas/database/migrations/015_create_settings_table.sql
\i c:/Syscare Projects/digital-business-card-saas/database/migrations/016_create_business_cards_table.sql
\i c:/Syscare Projects/digital-business-card-saas/database/migrations/017_create_card_social_links_table.sql
\i c:/Syscare Projects/digital-business-card-saas/database/migrations/018_create_card_gallery_table.sql
\i c:/Syscare Projects/digital-business-card-saas/database/migrations/019_create_nfc_cards_table.sql
\i c:/Syscare Projects/digital-business-card-saas/database/migrations/020_create_contacts_table.sql
\i c:/Syscare Projects/digital-business-card-saas/database/migrations/021_create_analytics_table.sql
\i c:/Syscare Projects/digital-business-card-saas/database/migrations/022_create_transactions_table.sql
\i c:/Syscare Projects/digital-business-card-saas/database/migrations/023_create_role_permissions_table.sql
\i c:/Syscare Projects/digital-business-card-saas/database/migrations/024_create_nfc_products_table.sql
\i c:/Syscare Projects/digital-business-card-saas/database/migrations/025_link_nfc_orders_to_products.sql
\i c:/Syscare Projects/digital-business-card-saas/database/migrations/026_extend_payments_for_manual_review.sql
\i c:/Syscare Projects/digital-business-card-saas/database/migrations/027_create_payouts_table.sql
\i c:/Syscare Projects/digital-business-card-saas/database/migrations/028_create_withdrawals_table.sql
\i c:/Syscare Projects/digital-business-card-saas/database/migrations/029_create_affiliate_program_tables.sql
\i c:/Syscare Projects/digital-business-card-saas/database/migrations/030_create_coupon_management_tables.sql
\i c:/Syscare Projects/digital-business-card-saas/database/migrations/031_create_saved_reports_tables.sql
\i c:/Syscare Projects/digital-business-card-saas/database/migrations/032_seed_platform_settings_and_permissions.sql
\i c:/Syscare Projects/digital-business-card-saas/database/migrations/033_create_auth_sessions_table.sql
\i c:/Syscare Projects/digital-business-card-saas/database/migrations/034_create_appointments_table.sql
\i c:/Syscare Projects/digital-business-card-saas/database/migrations/035_add_category_to_nfc_products.sql
