CREATE TABLE plans (
  id SERIAL PRIMARY KEY,
  name VARCHAR(150) NOT NULL UNIQUE,
  price NUMERIC(12, 2) NOT NULL DEFAULT 0.00,
  billing_interval VARCHAR(50) NOT NULL DEFAULT 'monthly',
  vcard_limit INTEGER NOT NULL DEFAULT 1,
  nfc_limit INTEGER NOT NULL DEFAULT 0,
  analytics_limit INTEGER NOT NULL DEFAULT 0,
  features JSONB DEFAULT '{}'::jsonb,
  status VARCHAR(50) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);
