BEGIN;
INSERT INTO vcard_templates (id,name,description,preview_url,template_json,is_public,created_at,updated_at) VALUES
(1,'Style Boutique','Elegant lifestyle and boutique VCard.','../public-vcard/final-01-boutique.html','{"finalized":true,"designKey":"boutique","category":"Fashion, Retail & Lifestyle","layout":"final-01","colors":{"primary":"#fff5f7","accent":"#df5b80"}}',TRUE,NOW(),NOW()),
(2,'Creative Studio','Creative portfolio VCard for designers and media professionals.','../public-vcard/final-02-creative.html','{"finalized":true,"designKey":"creative","category":"Creative & Media","layout":"final-02","colors":{"primary":"#171a1f","accent":"#ffd20a"}}',TRUE,NOW(),NOW()),
(3,'Technology Expert','Technology VCard for developers and IT specialists.','../public-vcard/final-03-technology.html','{"finalized":true,"designKey":"technology","category":"Technology & IT","layout":"final-03","colors":{"primary":"#111111","accent":"#b8ff00"}}',TRUE,NOW(),NOW()),
(4,'Medical Professional','Healthcare VCard for medical and wellness professionals.','../public-vcard/final-04-medical.html','{"finalized":true,"designKey":"medical","category":"Healthcare & Wellness","layout":"final-04","colors":{"primary":"#edf2f7","accent":"#0f8790"}}',TRUE,NOW(),NOW()),
(5,'Legal Counsel','Premium VCard for legal and finance professionals.','../public-vcard/final-05-legal.html','{"finalized":true,"designKey":"legal","category":"Legal & Finance","layout":"final-05","colors":{"primary":"#151515","accent":"#ce9454"}}',TRUE,NOW(),NOW()),
(6,'Event Planner','Event and entertainment services VCard.','../public-vcard/final-06-events.html','{"finalized":true,"designKey":"events","category":"Events & Entertainment","layout":"final-06","colors":{"primary":"#31003f","accent":"#ff2da9"}}',TRUE,NOW(),NOW()),
(7,'Real Estate Professional','Property VCard for realtors and developers.','../public-vcard/final-07-property.html','{"finalized":true,"designKey":"property","category":"Real Estate & Property","layout":"final-07","colors":{"primary":"#f1f2e9","accent":"#16815d"}}',TRUE,NOW(),NOW()),
(8,'Corporate Trainer','VCard for trainers, coaches and educators.','../public-vcard/final-08-trainer.html','{"finalized":true,"designKey":"trainer","category":"Education & Training","layout":"final-08","colors":{"primary":"#000000","accent":"#d49650"}}',TRUE,NOW(),NOW()),
(9,'Automotive Showroom','Automotive VCard for dealers and workshops.','../public-vcard/final-09-automotive.html','{"finalized":true,"designKey":"automotive","category":"Automotive & Transport","layout":"final-09","colors":{"primary":"#000000","accent":"#ed1c24"}}',TRUE,NOW(),NOW()),
(10,'Corporate Executive','Executive VCard for corporate professionals.','../public-vcard/final-10-corporate.html','{"finalized":true,"designKey":"corporate","category":"Corporate & Business","layout":"final-10","colors":{"primary":"#0b3942","accent":"#a1ff67"}}',TRUE,NOW(),NOW())
ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name,description=EXCLUDED.description,preview_url=EXCLUDED.preview_url,template_json=EXCLUDED.template_json,is_public=TRUE,updated_at=NOW();
UPDATE vcards SET template_id=CASE WHEN template_id=11 THEN 6 WHEN template_id=12 THEN 5 WHEN template_id=13 THEN 9 WHEN template_id=14 THEN 1 WHEN template_id=15 THEN 2 WHEN template_id=16 THEN 7 WHEN template_id=17 THEN 8 WHEN template_id=18 THEN 4 WHEN template_id=19 THEN 10 ELSE 10 END WHERE template_id>10;
DELETE FROM vcard_templates WHERE id NOT BETWEEN 1 AND 10;
UPDATE plans SET features=CASE WHEN jsonb_typeof(COALESCE(features,'{}'::jsonb))='object' THEN jsonb_set(COALESCE(features,'{}'::jsonb),'{templateIds}','[1,2,3,4,5,6,7,8,9,10]'::jsonb,TRUE) ELSE jsonb_build_object('benefits',COALESCE(features,'[]'::jsonb),'vcardFeatures','["basic-details"]'::jsonb,'templateIds','[1,2,3,4,5,6,7,8,9,10]'::jsonb) END;
SELECT setval(pg_get_serial_sequence('vcard_templates','id'),10,TRUE);
COMMIT;
